version: '3'
services:

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: welcome
      MONGO_INITDB_DATABASE: idv-local
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017

  verification-context-app:
    image: michaelruocco/verification-context-spring-app
    container_name: verification-context-app
    mem_limit: 2048m
    mem_reservation: 2048m
    ports:
      - 8081:80
    environment:
      - SERVER_PORT=80
      - AWS_ACCESS_KEY=abc
      - AWS_SECRET_KEY=123
      - REDIS_ENDPOINT_URI=redis://redis:6379
      - MONGO_CONNECTION_STRING=mongodb://idv:welcome01@mongo:27017/idv-local
      - SPRING_PROFILES_ACTIVE=local
      - REQUEST_LOGGING_ENABLED=false
      - RESPONSE_LOGGING_ENABLED=false
    depends_on:
      - redis
      - mongo