version: '3'
services:

  dynamo-db:
    image: amazon/dynamodb-local:latest
    container_name: dynamo-db

  create-dynamo-db-tables:
    image: mesosphere/aws-cli
    volumes:
      - ./localstack/tables:/tmp
    environment:
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=123
      - AWS_DEFAULT_REGION=eu-west-1
    entrypoint: /bin/sh -c "chmod +x /tmp/create-tables.sh; /tmp/create-tables.sh;"
    depends_on:
      - dynamo-db

  redis:
    image: redis
    container_name: redis

  verification-context-app:
    image: michaelruocco/verification-context-spring-app
    container_name: verification-context-app
    mem_limit: 1024m
    mem_reservation: 1024m
    ports:
      - 8081:80
    environment:
      - SERVER_PORT=80
      - AWS_ACCESS_KEY=abc
      - AWS_SECRET_KEY=123
      - AWS_DYNAMO_DB_ENDPOINT_URI=http://dynamo-db:8000
      - REDIS_ENDPOINT_URI=redis://redis:6379
      - SPRING_PROFILES_ACTIVE=local
      - REQUEST_LOGGING_ENABLED=false
      - RESPONSE_LOGGING_ENABLED=false
    depends_on:
      - create-dynamo-db-tables
      - redis