version: '3'
services:

  aws-services:
    image: localstack/localstack:latest
    container_name: aws-services
    volumes:
      - ./localstack/scripts:/docker-entrypoint-initaws.d
      - ./localstack/tables:/opt/tables
    environment:
      - DEFAULT_REGION=eu-west-1
      - SERVICES=dynamodb

  redis:
    image: redis
    container_name: redis

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: welcome
      MONGO_INITDB_DATABASE: idv
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  verification-context-app:
    image: michaelruocco/verification-context-spring-app
    container_name: verification-context-app
    ports:
      - 8081:80
    environment:
      - SERVER_PORT=80
      - AWS_ACCESS_KEY=abc
      - AWS_SECRET_KEY=123
      - AWS_DYNAMO_DB_ENDPOINT_URI=http://aws-services:4566
      - REDIS_ENDPOINT_URI=redis://redis:6379
      - MONGO_CONNECTION_STRING=mongodb://idv:welcome01@mongo:27017/idv
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      - aws-services
      - redis
      - mongo