version: '3'
services:

  elk:
    image: sebp/elk
    container_name: elk
    ports:
      - 5601:5601
    volumes:
      - ./elastic/logstash/pipeline.conf:/etc/logstash/conf.d/pipeline.conf:ro

  filebeat:
    image: elastic/filebeat:7.9.3
    container_name: filebeat
    restart: on-failure
    user: root
    volumes:
      - ./elastic/filebeat/docker.filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elk

  redis:
    image: redis
    container_name: redis

  mongo:
    image: mongo
    container_name: context-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: welcome
      MONGO_INITDB_DATABASE: idv-local
    ports:
      - 27018:27017
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  verification-context-app:
    image: michaelruocco/verification-context-spring-app
    container_name: verification-context-app
    mem_limit: 2048m
    mem_reservation: 2048m
    ports:
      - 8081:80
    environment:
      - SERVER_PORT=80
      - SPRING_PROFILES_ACTIVE=simple-logging
      - REDIS_ENDPOINT_URI=redis://redis:6379
      - MONGO_CONNECTION_STRING=mongodb://idv:welcome01@context-mongo:27017/idv-local
      - EXTERNAL_DATA_TIMEOUT=1000
      - EXTERNAL_PHONE_NUMBER_DELAY=750
      - EXTERNAL_EMAIL_ADDRESS_DELAY=500
      - REQUEST_LOGGING_ENABLED=true
      - RESPONSE_LOGGING_ENABLED=true
    depends_on:
      - redis
      - mongo